services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bricolage
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
