services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - bricolage-network
    profiles:
      - frontend

  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "2020:2020"
    networks:
      - bricolage-network
    profiles:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bricolage
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - bricolage-network
    profiles:
      - db
      - backend
      - frontend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - bricolage-network
    profiles:
      - db
      - backend
      - frontend

volumes:
  mysql_data:

networks:
  bricolage-network:
    driver: bridge
