name: "Backend CI/CD"

on:
  push:
    branches:
      - main
    paths:
      - back/**
  pull_request:
    branches:
      - main
    paths:
      - back/**

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x gradlew

      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
